version: '3.3'

networks:
  codechat-net:
    driver: bridge

services:
  minha-aplicacao:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - /data/instances:/codechat/instances
    command: ['node', './dist/src/main.js']
